---
- name: Set OS dependent variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    ansible_distribution_lts_offset: >-
      {{
        ansible_distribution_major_version|int % 2
        if ansible_distribution == "Ubuntu"
        else 0
      }}
    ansible_distribution_lts_version: >-
      {{
        ansible_distribution_major_version|int -
        ansible_distribution_lts_offset|int
        if ansible_distribution == "Ubuntu"
        else ansible_distribution_version
      }}
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_lts_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - '{{ role_path }}/vars'
        - '{{ playbook_dir }}/vars'

- name: Override OS defaults
  block:
    - name: Define sshd_packages
      set_fact:
        sshd_packages: "{{ __sshd_packages }}"
      when: sshd_packages is not defined
    - name: Define sshd_config_owner
      set_fact:
        sshd_config_owner: "{{ __sshd_config_owner }}"
      when: sshd_config_owner is not defined
    - name: Define sshd_config_group
      set_fact:
        sshd_config_group: "{{ __sshd_config_group }}"
      when: sshd_config_group is not defined
    - name: Define sshd_config_mode
      set_fact:
        sshd_config_mode: "{{ __sshd_config_mode }}"
      when: sshd_config_mode is not defined
    - name: Define sshd_config_file
      set_fact:
        __sshd_config_file: "{{ sshd_config_file }}"
      when: sshd_config_file is defined
    - name: Define sshd_binary
      set_fact:
        sshd_binary: "{{ __sshd_binary }}"
      when: sshd_binary is not defined
    - name: Define sshd_service
      set_fact:
        sshd_service: "{{ __sshd_service }}"
      when: sshd_service is not defined
    - name: Define sshd_sftp_server
      set_fact:
        sshd_sftp_server: "{{ __sshd_sftp_server }}"
      when: sshd_sftp_server is not defined
    - name: Define sshd_sysconfig
      set_fact:
        sshd_sysconfig: "{{ __sshd_sysconfig }}"
      when: sshd_sysconfig is not defined
    - name: Define sshd_verify_hostkeys
      set_fact:
        # This mimics the macro body_option() in sshd_config.j2
        __sshd_verify_hostkeys: >
          {% if sshd_verify_hostkeys is defined %}
            {{ sshd_verify_hostkeys }}
          {% elif sshd_HostKey is defined %}
            {{ sshd_hostkey }}
          {% elif sshd['HostKey'] is defined %}
            {{ sshd['HostKey'] }}
          {% elif __sshd_defaults['HostKey'] is defined and not sshd_skip_defaults %}
            {{ __sshd_defaults['HostKey'] }}
          {% else %}
            {{ __sshd_verify_hostkeys }}
          {% endif %}
    - name: Define sshd_hostkey_owner
      set_fact:
        sshd_hostkey_owner: "{{ __sshd_hostkey_owner }}"
      when: sshd_hostkey_owner is not defined
    - name: Define sshd_hostkey_group
      set_fact:
        sshd_hostkey_group: "{{ __sshd_hostkey_group }}"
      when: sshd_hostkey_group is not defined
    - name: Define sshd_hostkey_mode
      set_fact:
        sshd_hostkey_mode: "{{ __sshd_hostkey_mode }}"
